# Numpy
 ## 넘파이 ndarray 개요

In [72]:
import numpy as np

In [73]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)



array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


## ndarray 데이터 타입

In [74]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


- 같은 데이터 타입끼리만 연산 가능
> 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [75]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- ndarray 내 데이터 타입 변경 : astype()
> float형 -> int형 : 소수점 이하 제거됨

In [76]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray 생성: arrange, zeros, ones
>  arange(): array를 range()로 표현
   > - 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해 줌.


In [77]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


> zeros() : 튜플 형태의 shape 값을 입력 시 모든 값을 0으로 채운 해당 shpae를 가진 ndarray를 반환
> - defauly dtype: float64

> ones(): 튜플형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shpae를 가진 ndarray로 반환
> - defauly dtype: float64

In [78]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarry의 차원과 크기를 변경: reshape()
- 지정된 사이즈로만 변경이 가능
> (10,) -> (2,5), (5,2) 가능// (10,) -> (4,3) 불가능 
- reshape()에 -1값을 인자로 적용한 경우
> array1 -> array3 : 고정된 5개의 로우에 맞는 컬럼을 자동으로 새롭게 생성해 변환
> - -1을 사용하더라도 화환될 수 없는 형태는 변환될 수 없음

In [79]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(2,5)
print('array2.shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


#### reshape(-1,1): 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨.
- 여러개의 넘파이는 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태로 통일~유용하게 사용

In [80]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) #tolist: ndarray를list 자료형으로 바꿈

# 3 -> 2
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5.shape:', array5.shape)

array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6.shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(lndexing)
- 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨.
- 슬라이싱(slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식.':'기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1위치에 있는 데이터의 ndarray를 반환합니다. 예를 들어 1:5라고 하면 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환
- 팬시 인덱싱(Fancy Indexing):일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환합니다.
- 불린 인덱싱(boolen lndexing): 특정 조건에 해당하는지 여부인 true/false 값 인덱싱 집합을 기반으로 true에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다

#### 단일 값 추출: 한개의 데이터만을 추출하는 방법
- 1차원 ndarray
> - index는 0부터 시작하므로 array[n]은 데이터 중 n번째에 위치한 데이터 값을 의미

In [81]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:', value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


> - index -1: 맨뒤의 데이터값을 의미

In [82]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


> - ndarray내의 데이터 값 수정

In [83]:
array1[0] = 9
array1[1] = 0
print('array1:', array1)

array1: [9 0 3 4 5 6 7 8 9]


- 다차원 ndarray
> - 넘파이의 다차원 ndarray는 axis 구분을 가짐
> - 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근

In [84]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


> - axis=0: 로우 방향의 축을 의미
> - axis=1: 칼럼 방향의 축을 의미
> - ndarray에서는 row,col이 사용되지 않음 즉, [row=0,col=0]=[axis=0,axis=1]

#### 슬라이싱 
- ':'기호를 이용해 연속한 데이터를 슬라이싱해서 추출 가능
> - 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략 가능
> - 단일 데이터 값을 제외한 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입


In [85]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


> 1차원 ndarray 슬라이싱

In [86]:
array1 =  np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


> 2차원 ndarray 슬라이싱

In [87]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2]\n', array2d[0:2,0:2])
print('array2d[1:3,1:3]\n', array2d[1:3,1:3])
print('array2d[1:3,:]\n', array2d[1:3,:])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,1:]\n', array2d[:2,1:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,1:3]
 [[5 6]
 [8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


> -  다차원 ndarray에서 뒤에 오는 인덱스를 없앴을 때: 1차원 ndarray 반환

In [88]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape :', array2d[0].shape ,'array2d[1] shape:',array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape : (3,) array2d[1] shape: (3,)


#### 펜시 인덱싱
- 리스트나 ndarray로 "인덱스 집합"을 지정하면 해당 위치의 인덱스에 해당하는 ndarray 반환하는 인덱싱 방식

In [89]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2] 
print('array2d[[0,1],2]=>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],2]=>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱
- 조건 필터링&검색 동시 가능
> - 예제의 경우 array1d > 5인 데이터값을 찾는 조건문
> -
array([False, False, False, False, False,  True,  True,  True,  True])에서 False가 있는 인덱스 0~4는 무시하고, 인덱스 [5,6,7,8]이 만들어지고 이 위체 해당하는 데이터 세트 [6,7,8,9] 반환


In [90]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d >5 Boolean Indexing 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',  array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [91]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [92]:
boolean_indexes =np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


### 행렬의 정렬: sort(), argsort()
- np.sort() & ndarray.sort() - 기본적으로 오름차순 정렬

> 1차원 행렬의 경우
>> - 내림차순 정렬: [::-1] 적용(np.sort()[::-1]) 

> 2차원 행렬의 경우
>> - axis 축 값 설정을 통해 로우 방향,또는 칼럼 방향으로 정렬 수행

- np.sort(): 넘파이에서 sort()를 호출
> - 원 행렬은 그대로 유지, 반환 값: 원행렬의 정렬된 행렬
- ndarray.sort(): 행렬 자체에서 sort()를 호출
> - 원 행렬 자체를 정렬한 형태로 변환, 반환 값: None

In [93]:
org_array = np.array([3,1,9,5])
print('원본행렬:', org_array)

# np.sort()
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

#ndarray.sort()
sort_array2 = org_array.sort()
print('org_array.sort 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort 호출 후 원본 행렬:', org_array)

원본행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort 호출 후 반환된 행렬: None
org_array.sort 호출 후 원본 행렬: [1 3 5 9]


In [94]:
#1차원
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [95]:
#2차원 이상
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)


로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 '인덱스'를 반환하기: argsort()
- np.argsort()
> - 원본 행렬이 정렬되었을 때,  기존 원본 행렬의 원소에 대한 "인덱스"를 필요로 할때 이용
> -  정렬 행렬의 원본 행렬 Index를 ndarray 형으로 반환
![image1.png](image1.png.) 

In [100]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [101]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## ※ndarray는 메타 데이터(RDBMS의 TABLE 칼럼 or 판다스 DataFrame 칼럼)를 가질 수 없음
> - 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 함 

In [103]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적가 전치 행렬 구하기
- np.dot(): 행렬 내적(행렬 곱) ex) 두 행렬 A와 B의 내적
![image2.png](image2.png) 

In [107]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product= np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬
원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬

In [109]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
